### ISSUE TITLE
parser ignores array[0] if value is 0

### ISSUE THREAD

**Issue by bnairyb** [rjrodger/jsonic#10]
using node 4.2.4 attempting to parse an array where the value of index[0] is 0 - parser drops the index and shortens the array length by 1.

Examples in node repl:

> foo = '{foo:"bar", arr:[0,0]}'
> '{foo:"bar", arr:[0,0]}'
> jsonic(foo)
> { foo: 'bar', arr: [ 0 ] }
> foo = '{foo:"bar", arr:[0,0,0]}'
> '{foo:"bar", arr:[0,0,0]}'
> jsonic(foo)
> { foo: 'bar', arr: [ 0, 0 ] }
> foo = '{foo:"bar", arr:[0,0,1]}'
> '{foo:"bar", arr:[0,0,1]}'
> jsonic(foo)
> { foo: 'bar', arr: [ 0, 1 ] }
> foo = '{foo:"bar", arr:[1,0,1]}'
> '{foo:"bar", arr:[1,0,1]}'
> jsonic(foo)
> { foo: 'bar', arr: [ 1, 0, 1 ] }
> foo = '{foo:"bar", arr:[0,1,1]}'
> '{foo:"bar", arr:[0,1,1]}'
> jsonic(foo)
> { foo: 'bar', arr: [ 1, 1 ] }

**Comment by rjrodger** [comment]
This is now fixed
