### ISSUE TITLE
pegjs does not generate a fresh jsonic-parser.js

### ISSUE THREAD

**Issue by lilsweetcaligula** [rjrodger/jsonic#23]
There seems to be some sort of issue with pegjs, - the `--export-var` option of pegjs in particular.

Running `$ npm run-script build` outputs a warning:
> Can't use the -e/--export-var option with the "commonjs" module format.

The `jsonic-parser.js` file is not being generated:
> $ git status
> On branch master
> Your branch is up to date with 'origin/master'.
>
> nothing to commit, working tree clean

Specifying `--format globals` or building without the `--export-var` option remedies the problem and generates a new `jsonic-parser.js` file. However, this change breaks the rest of the `build` script.

**Comment by rjrodger** [comment]
So... very soon there will be a new hand-written parser, which should make this issue moot.
https://github.com/rjrodger/jsonic/blob/nextgen/jsonic.ts#L1588
