### ISSUE TITLE
Cant have spaces after the property name and before the :

### ISSUE THREAD

**Issue by PAEz** [rjrodger/jsonic#6]
As the title states there cant be spaces after the property name and before the `:`, unless the property is in double quotes.
If you cant fix it you should be it in your rules list.

**Comment by rjrodger** [comment]
this should be supported

**Comment by moos** [comment]
:+1:  This is more of a bug as regular JSON allows it:

JSON.parse('{"a"    :   11}')
Object {a: 11}

**Comment by avrelaun** [comment]
Same problem here.

**Comment by rjrodger** [comment]
Thank You!
